services:
  - type: web
    name: Pitch Visualizer
    plan: free
    runtime: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
